apiVersion: v1
kind: Service
metadata:
  name: multisubs-backend
  namespace: multisubs
  labels:
    app: multisubs-backend
    app.kubernetes.io/name: multisubs-backend
    app.kubernetes.io/part-of: multisubs-platform
spec:
  type: ClusterIP
  selector:
    app: multisubs-backend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
